### ISSUE TITLE
How to fetch key value without looping over the list of keys?

### ISSUE THREAD

**Issue by Ambrevar** [metawilm/cl-custom-hash-table#2]
Running `(gethash FOO-KEY HASH-TABLE)` returns the value corresponding to _some_ `BAR-KEY` which may not be the same as `FOO-KEY`. (All we know is that it satisfies the hash function).

Now is there a way to retrieve BAR-KEY by just knowing FOO-KEY, without looping over the whole list of keys?

**Comment by metawilm** [comment]
The keys are checked using the equality function, but they also must have the same hash value.
Can you perhaps give example code?

**Comment by metawilm** [comment]
Also, is the `gethash` call wrapped inside `with-custom-hash-table`?

**Comment by Ambrevar** [comment]
Sure, they are.

```lisp
(defclass entry ()
  ((url :accessor url :initarg :url)
   (title :accessor title :initarg :title)))

(defun entry-equal-p (a b)
  (string= (url a) (url b)))

(defun entry-hash (a)
  (sxhash (url a)))

(cl-custom-hash-table:define-custom-hash-table-constructor make-entry-hash-table
  :test entry-equal-p
  :hash-function entry-hash)

(defun test ()
  (cl-custom-hash-table:with-custom-hash-table
    (let ((h (make-entry-hash-table))
          (entry (make-instance 'entry :url "http://foo" :title "foo")))
      (setf (gethash entry h) 17)
      (let ((entry (make-instance 'entry :url "http://foo" :title "bar")))
        (gethash entry h)))))

```

My question is: how can I access the original entry within the second let?  My new `entry` has a different title, and sure I can get the value corresponding to it, but how can I get the original key?

**Comment by metawilm** [comment]
It seems to me that what you are asking for is not something that hash tables provide. Whether you use `cl-custom-hash-table` or regular `eql/equal/equalp` hash table does not make a difference. The only way to find the corresponding key is to iterate over all of them.

But if you store the original key with the value, you have it directly available: `(setf (gethash entry h) (cons h 17))`.

**Comment by Ambrevar** [comment]
That's what I was afraid of...  Thanks for confirming! :)
